# Generated by Django 6.0.4 on 2026-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('scope_id', models.PositiveIntegerField()),
                ('exam_year', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('scope', 'scope_id', 'exam_year', 'subject')},
            },
        ),
    ]
