# Generated by Django 6.0.4 on 2026-04-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticssnapshot',
            options={'verbose_name': 'Снимок аналитики', 'verbose_name_plural': 'Снимки аналитики'},
        ),
    ]
