# Generated by Django 5.2.15 on 2026-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_analyticssnapshot_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        db_index=True, max_length=8, verbose_name="Тип экзамена"
                    ),
                ),
                (
                    "subject_key",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Ключ предмета"
                    ),
                ),
                (
                    "task_number",
                    models.PositiveIntegerField(verbose_name="Номер задания"),
                ),
                (
                    "document_year",
                    models.PositiveIntegerField(
                        db_index=True, default=2026, verbose_name="Год документа"
                    ),
                ),
                (
                    "official_task_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Официальное название"
                    ),
                ),
                (
                    "section",
                    models.CharField(blank=True, max_length=512, verbose_name="Раздел"),
                ),
                (
                    "subsection",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Подраздел"
                    ),
                ),
                ("topic", models.CharField(max_length=512, verbose_name="Тема")),
                (
                    "subtopic",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Подтема"
                    ),
                ),
                (
                    "fgos_class_start",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Класс изучения"
                    ),
                ),
                (
                    "fgos_class_repeat",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Классы повторения"
                    ),
                ),
                (
                    "fgos_classes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Классы ФГОС"
                    ),
                ),
                (
                    "fgos_exam_class",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Класс проверки"
                    ),
                ),
                (
                    "fipi_content_code",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Код элемента содержания",
                    ),
                ),
                (
                    "requirement_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код требования"
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код умения"
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Проверяемое умение"
                    ),
                ),
                (
                    "competency",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Компетенция"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Сложность"
                    ),
                ),
                (
                    "exam_part",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Часть экзамена"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Макс. балл",
                    ),
                ),
                (
                    "related_tasks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Связанные задания"
                    ),
                ),
                (
                    "previous_topics",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Предыдущие темы"
                    ),
                ),
                (
                    "next_topics",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Последующие темы"
                    ),
                ),
                (
                    "teaching_hours",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Часы изучения"
                    ),
                ),
                (
                    "recommended_practice_hours",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Часы практики"
                    ),
                ),
                (
                    "recommended_control",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Контроль"
                    ),
                ),
                (
                    "expected_growth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Ожидаемый прирост, %",
                    ),
                ),
                (
                    "source_document",
                    models.CharField(max_length=255, verbose_name="Источник"),
                ),
                (
                    "document_version",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Версия документа"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.5,
                        max_digits=4,
                        verbose_name="Достоверность",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырые данные"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Знание о задании (ФИПИ)",
                "verbose_name_plural": "База знаний ФИПИ (задания)",
                "ordering": ("exam_type", "subject_key", "task_number"),
                "indexes": [
                    models.Index(
                        fields=["exam_type", "subject_key", "task_number"],
                        name="analytics_t_exam_ty_218118_idx",
                    ),
                    models.Index(fields=["skill"], name="analytics_t_skill_1e278f_idx"),
                    models.Index(
                        fields=["fipi_content_code"],
                        name="analytics_t_fipi_co_e0d137_idx",
                    ),
                ],
                "unique_together": {
                    ("exam_type", "subject_key", "task_number", "document_year")
                },
            },
        ),
    ]
