# Generated by Django 6.0.4 on 2026-04-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name': 'Министерство', 'verbose_name_plural': 'Министерства'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('name',), 'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
    ]
