# Generated by Django 6.0.4 on 2026-04-28 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('ege', 'ЕГЭ'), ('oge', 'ОГЭ')], max_length=8)),
                ('code', models.CharField(max_length=8)),
                ('subject', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('year', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'ordering': ('-exam_date', 'subject'),
                'unique_together': {('exam_type', 'code', 'exam_date')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=16)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organizations.school')),
            ],
            options={
                'ordering': ('full_name',),
                'unique_together': {('school', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('passed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='exams.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='exams.student')),
            ],
            options={
                'indexes': [models.Index(fields=['exam', 'task_number', 'value'], name='exams_taskr_exam_id_c3be35_idx')],
                'unique_together': {('student', 'exam', 'task_number')},
            },
        ),
    ]
