# Generated by Django 6.0.4 on 2026-04-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-exam_date', 'subject'), 'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Результат экзамена', 'verbose_name_plural': 'Результаты экзаменов'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('full_name',), 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='taskresult',
            options={'verbose_name': 'Результат задания', 'verbose_name_plural': 'Результаты заданий'},
        ),
    ]
