# Generated by Django 6.0.4 on 2026-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_options_alter_examresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='short_answer_raw',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='source_row',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
