# Generated by Django 6.0.4 on 2026-04-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examresult_short_answer_raw_examresult_source_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='long_answer_tasks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='primary_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='examresult',
            name='school_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='examresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='examresult',
            name='short_answer_tasks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
