# Generated by Django 5.2.9 on 2026-04-30

from django.db import migrations, models


def seed_thresholds(apps, schema_editor):
    EgePassingThreshold = apps.get_model("exams", "EgePassingThreshold")
    subjects = [
        {"subject_key": "russian", "minimum_score": 24, "minimum_grade": None},
        {"subject_key": "math_profile", "minimum_score": 27, "minimum_grade": None},
        {"subject_key": "math_basic", "minimum_score": None, "minimum_grade": 3},
        {"subject_key": "social", "minimum_score": 42, "minimum_grade": None},
        {"subject_key": "informatics", "minimum_score": 40, "minimum_grade": None},
        {"subject_key": "physics", "minimum_score": 36, "minimum_grade": None},
        {"subject_key": "chemistry", "minimum_score": 36, "minimum_grade": None},
        {"subject_key": "biology", "minimum_score": 36, "minimum_grade": None},
        {"subject_key": "history", "minimum_score": 32, "minimum_grade": None},
        {"subject_key": "literature", "minimum_score": 32, "minimum_grade": None},
        {"subject_key": "geography", "minimum_score": 37, "minimum_grade": None},
        {"subject_key": "foreign_language", "minimum_score": 22, "minimum_grade": None},
    ]
    for year in (2023, 2024, 2025):
        for item in subjects:
            EgePassingThreshold.objects.update_or_create(
                year=year,
                subject_key=item["subject_key"],
                defaults={
                    "minimum_score": item["minimum_score"],
                    "minimum_grade": item["minimum_grade"],
                },
            )


def unseed_thresholds(apps, schema_editor):
    EgePassingThreshold = apps.get_model("exams", "EgePassingThreshold")
    EgePassingThreshold.objects.filter(year__in=[2023, 2024, 2025]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_examresult_long_answer_tasks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EgePassingThreshold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(db_index=True, verbose_name="Год")),
                (
                    "subject_key",
                    models.CharField(
                        choices=[
                            ("russian", "Русский язык"),
                            ("math_profile", "Математика (профиль)"),
                            ("math_basic", "Математика (база)"),
                            ("social", "Обществознание"),
                            ("informatics", "Информатика"),
                            ("physics", "Физика"),
                            ("chemistry", "Химия"),
                            ("biology", "Биология"),
                            ("history", "История"),
                            ("literature", "Литература"),
                            ("geography", "География"),
                            ("foreign_language", "Иностранный язык"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "minimum_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Минимальный балл",
                    ),
                ),
                (
                    "minimum_grade",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Минимальная оценка"),
                ),
            ],
            options={
                "verbose_name": "Минимальный порог ЕГЭ",
                "verbose_name_plural": "Минимальные пороги ЕГЭ",
                "ordering": ("-year", "subject_key"),
                "unique_together": {("year", "subject_key")},
            },
        ),
        migrations.RunPython(seed_thresholds, unseed_thresholds),
    ]
