# Generated by Django 5.2.9 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_egepassingthreshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamTaskTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("ege", "ЕГЭ"), ("oge", "ОГЭ")],
                        max_length=8,
                        verbose_name="Тип экзамена",
                    ),
                ),
                ("subject_key", models.CharField(db_index=True, max_length=64, verbose_name="Ключ предмета")),
                ("task_number", models.PositiveIntegerField(verbose_name="Номер задания")),
                ("topic", models.CharField(max_length=512, verbose_name="Тема")),
                ("grade_range", models.JSONField(blank=True, default=list, verbose_name="Классы")),
            ],
            options={
                "verbose_name": "Тема задания экзамена",
                "verbose_name_plural": "Темы заданий экзаменов",
                "ordering": ("exam_type", "subject_key", "task_number"),
                "unique_together": {("exam_type", "subject_key", "task_number")},
            },
        ),
    ]
