# Generated by Django 5.2.9 on 2026-05-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examtasktopic'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'exam_date'], name='exams_exam_exam_ty_054467_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'code'], name='exams_exam_exam_ty_aa1204_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'score'], name='exams_examr_exam_id_da87ae_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'passed'], name='exams_examr_exam_id_790b07_idx'),
        ),
        migrations.AddIndex(
            model_name='taskresult',
            index=models.Index(fields=['exam', 'student'], name='exams_taskr_exam_id_16c71a_idx'),
        ),
    ]
