# Generated by Django 5.2.10 on 2026-05-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0007_alter_examresult_exam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examresult",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="exams.exam",
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="long_answer_tasks",
            field=models.TextField(blank=True, verbose_name="Задания с развернутым ответом"),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="passed",
            field=models.BooleanField(default=False, verbose_name="Сдал"),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="primary_score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Первичный балл"
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="school_code",
            field=models.CharField(blank=True, max_length=32, verbose_name="Код ОО"),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Балл"
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="short_answer_raw",
            field=models.TextField(blank=True, verbose_name="Сырые краткие ответы"),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="short_answer_tasks",
            field=models.TextField(blank=True, verbose_name="Задания с кратким ответом"),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="source_row",
            field=models.JSONField(blank=True, default=dict, verbose_name="Исходная строка"),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="exams.student",
                verbose_name="Ученик",
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="student_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="total_score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Итоговый балл"
            ),
        ),
    ]
