# Generated by Django 5.2.15 on 2026-07-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_alter_examresult_exam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("ege", "ЕГЭ"), ("oge", "ОГЭ"), ("vpr", "ВПР")], max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="examtasktopic",
            name="exam_type",
            field=models.CharField(
                choices=[("ege", "ЕГЭ"), ("oge", "ОГЭ"), ("vpr", "ВПР")],
                max_length=8,
                verbose_name="Тип экзамена",
            ),
        ),
    ]
