# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0008_alter_examresult_exam_and_more"),
        ("exams", "0008_examtype_add_vpr"),
    ]

    operations = []
