from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordChangeView
from django.views.generic import RedirectView
from django.urls import path

from users.legal_views import (
    PrivacyPolicyView,
    SchoolDocumentDownloadView,
    SchoolDocumentsView,
    TermsOfAccessView,
)
from users.protocol_upload_views import (
    DistrictDownloadEgeProtocolSampleView,
    DistrictDownloadOgeProtocolSampleView,
    DistrictProtocolExamDeleteView,
    DistrictProtocolUploadRevertView,
    DistrictUploadEgeProtocolsView,
    DistrictUploadOgeProtocolsView,
    SchoolDownloadEgeProtocolSampleView,
    SchoolDownloadOgeProtocolSampleView,
    SchoolProtocolExamDeleteView,
    SchoolProtocolUploadRevertView,
    SchoolUploadEgeProtocolsView,
    SchoolUploadOgeProtocolsView,
)
from users.web_views import (
    DownloadDistrictAnalyticNoteDocxView,
    DownloadDistrictGiaSummaryDocxView,
    DownloadDistrictGiaSummaryPdfView,
    DownloadDistrictGiaSummaryXlsxView,
    DownloadDistrictInfoStatDocxView,
    DownloadDistrictManagementDocxView,
    DownloadDistrictMoReportDocxView,
    DownloadDistrictSchoolComparisonDocxView,
    DownloadDistrictSubjectNoteDocxView,
    DownloadSchoolDeputyReportDocxView,
    DownloadSchoolDeputyReportPdfView,
    DownloadSchoolDeputyReportXlsxView,
    DownloadSchoolMoReportDocxView,
    DownloadSchoolMoReportPdfView,
    DownloadSchoolSubjectNoteDocxView,
    DownloadSchoolSubjectNotePdfView,
    DownloadSchoolAnalyticNoteDocxView,
    DownloadSchoolAnalyticNotePdfView,
    DistrictDashboardView,
    DistrictSchoolDashboardView,
    DistrictStudentWorkView,
    SchoolStudentWorkView,
    DownloadSchoolExamPdfView,
    DownloadSchoolExamPptxView,
    DownloadSchoolExamWordView,
    DownloadSchoolExamXlsxView,
    DownloadSchoolGiaSummaryView,
    DownloadSchoolInfoStatDocxView,
    DownloadSchoolInfoStatPdfView,
    DownloadSchoolInfoStatXlsxView,
    ExamTypeChoiceView,
    DistrictSubjectComparisonView,
    MinistryDashboardView,
    NoRoleView,
    OrganizationProfileView,
    ReportsHubView,
    RoleLoginView,
    RoleRedirectView,
    SchoolDashboardView,
    SupportQuestionView,
    VprPlaceholderView,
)

urlpatterns = [
    path("", RoleLoginView.as_view(), name="home-login"),
    path("logout/", LogoutView.as_view(next_page="home-login"), name="user-logout"),
    path(
        "cabinet/password-change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html",
            success_url="/cabinet/password-change/done/",
        ),
        name="cabinet-password-change",
    ),
    path(
        "cabinet/password-change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="cabinet-password-change-done",
    ),
    path("cabinet/", RoleRedirectView.as_view(), name="cabinet"),
    path("cabinet/exam-choice/", ExamTypeChoiceView.as_view(), name="cabinet-exam-choice"),
    path("cabinet/support-ask/", SupportQuestionView.as_view(), name="cabinet-support-ask"),
    path("cabinet/reports/", ReportsHubView.as_view(), name="cabinet-reports"),
    path("cabinet/profile/", OrganizationProfileView.as_view(), name="cabinet-profile"),
    path("cabinet/upload/ege/", SchoolUploadEgeProtocolsView.as_view(), name="cabinet-upload-ege"),
    path("cabinet/upload/ege/sample/", SchoolDownloadEgeProtocolSampleView.as_view(), name="cabinet-upload-ege-sample"),
    path("cabinet/upload/ege/revert/<int:session_id>/", SchoolProtocolUploadRevertView.as_view(), name="cabinet-upload-ege-revert"),
    path("cabinet/upload/ege/delete-exam/<int:exam_id>/", SchoolProtocolExamDeleteView.as_view(), name="cabinet-upload-ege-delete-exam"),
    path("cabinet/upload/oge/", SchoolUploadOgeProtocolsView.as_view(), name="cabinet-upload-oge"),
    path("cabinet/upload/oge/sample/", SchoolDownloadOgeProtocolSampleView.as_view(), name="cabinet-upload-oge-sample"),
    path("cabinet/upload/oge/revert/<int:session_id>/", SchoolProtocolUploadRevertView.as_view(), name="cabinet-upload-oge-revert"),
    path("cabinet/upload/oge/delete-exam/<int:exam_id>/", SchoolProtocolExamDeleteView.as_view(), name="cabinet-upload-oge-delete-exam"),
    path(
        "cabinet/upload/vpr/",
        RedirectView.as_view(pattern_name="vpr-upload", permanent=False),
        name="cabinet-upload-vpr",
    ),
    path("cabinet/district/upload/ege/", DistrictUploadEgeProtocolsView.as_view(), name="cabinet-district-upload-ege"),
    path("cabinet/district/upload/ege/sample/", DistrictDownloadEgeProtocolSampleView.as_view(), name="cabinet-district-upload-ege-sample"),
    path("cabinet/district/upload/ege/revert/<int:session_id>/", DistrictProtocolUploadRevertView.as_view(), name="cabinet-district-upload-ege-revert"),
    path("cabinet/district/upload/ege/delete-exam/<int:exam_id>/", DistrictProtocolExamDeleteView.as_view(), name="cabinet-district-upload-ege-delete-exam"),
    path("cabinet/district/upload/oge/", DistrictUploadOgeProtocolsView.as_view(), name="cabinet-district-upload-oge"),
    path("cabinet/district/upload/oge/sample/", DistrictDownloadOgeProtocolSampleView.as_view(), name="cabinet-district-upload-oge-sample"),
    path("cabinet/district/upload/oge/revert/<int:session_id>/", DistrictProtocolUploadRevertView.as_view(), name="cabinet-district-upload-oge-revert"),
    path("cabinet/district/upload/oge/delete-exam/<int:exam_id>/", DistrictProtocolExamDeleteView.as_view(), name="cabinet-district-upload-oge-delete-exam"),
    path("cabinet/oge/", RedirectView.as_view(url="/cabinet/?exam_type=oge", permanent=False), name="cabinet-oge"),
    path("cabinet/vpr/", VprPlaceholderView.as_view(), name="cabinet-vpr"),
    path("cabinet/no-role/", NoRoleView.as_view(), name="no-role"),
    path("cabinet/ministry/", MinistryDashboardView.as_view(), name="cabinet-ministry"),
    path("cabinet/district/", DistrictDashboardView.as_view(), name="cabinet-district"),
    path(
        "cabinet/district/subject/",
        DistrictSubjectComparisonView.as_view(),
        name="cabinet-district-subject",
    ),
    path(
        "cabinet/district/school/<int:school_id>/",
        DistrictSchoolDashboardView.as_view(),
        name="cabinet-district-school",
    ),
    path(
        "cabinet/district/result/<int:result_id>/",
        DistrictStudentWorkView.as_view(),
        name="cabinet-district-student-work",
    ),
    path("cabinet/school/", SchoolDashboardView.as_view(), name="cabinet-school"),
    path(
        "cabinet/school/result/<int:result_id>/",
        SchoolStudentWorkView.as_view(),
        name="cabinet-school-student-work",
    ),
    path("cabinet/school/export-word/", DownloadSchoolExamWordView.as_view(), name="cabinet-school-export-word"),
    path("cabinet/school/export-pptx/", DownloadSchoolExamPptxView.as_view(), name="cabinet-school-export-pptx"),
    path("cabinet/school/export-pdf/", DownloadSchoolExamPdfView.as_view(), name="cabinet-school-export-pdf"),
    path("cabinet/school/export-xlsx/", DownloadSchoolExamXlsxView.as_view(), name="cabinet-school-export-xlsx"),
    path("cabinet/school/export-gia-summary/", DownloadSchoolGiaSummaryView.as_view(), name="cabinet-school-export-gia-summary"),
    path("cabinet/school/export-info-stat-docx/", DownloadSchoolInfoStatDocxView.as_view(), name="cabinet-school-export-info-stat-docx"),
    path("cabinet/school/export-info-stat-pdf/", DownloadSchoolInfoStatPdfView.as_view(), name="cabinet-school-export-info-stat-pdf"),
    path("cabinet/school/export-info-stat-xlsx/", DownloadSchoolInfoStatXlsxView.as_view(), name="cabinet-school-export-info-stat-xlsx"),
    path("cabinet/school/export-analytic-note-docx/", DownloadSchoolAnalyticNoteDocxView.as_view(), name="cabinet-school-export-analytic-note-docx"),
    path("cabinet/school/export-analytic-note-pdf/", DownloadSchoolAnalyticNotePdfView.as_view(), name="cabinet-school-export-analytic-note-pdf"),
    path("cabinet/school/export-subject-note-docx/", DownloadSchoolSubjectNoteDocxView.as_view(), name="cabinet-school-export-subject-note-docx"),
    path("cabinet/school/export-subject-note-pdf/", DownloadSchoolSubjectNotePdfView.as_view(), name="cabinet-school-export-subject-note-pdf"),
    path("cabinet/school/export-mo-report-docx/", DownloadSchoolMoReportDocxView.as_view(), name="cabinet-school-export-mo-report-docx"),
    path("cabinet/school/export-mo-report-pdf/", DownloadSchoolMoReportPdfView.as_view(), name="cabinet-school-export-mo-report-pdf"),
    path("cabinet/school/export-deputy-report-docx/", DownloadSchoolDeputyReportDocxView.as_view(), name="cabinet-school-export-deputy-report-docx"),
    path("cabinet/school/export-deputy-report-pdf/", DownloadSchoolDeputyReportPdfView.as_view(), name="cabinet-school-export-deputy-report-pdf"),
    path("cabinet/school/export-deputy-report-xlsx/", DownloadSchoolDeputyReportXlsxView.as_view(), name="cabinet-school-export-deputy-report-xlsx"),
    path("cabinet/district/export-gia-summary-docx/", DownloadDistrictGiaSummaryDocxView.as_view(), name="cabinet-district-export-gia-summary-docx"),
    path("cabinet/district/export-gia-summary-pdf/", DownloadDistrictGiaSummaryPdfView.as_view(), name="cabinet-district-export-gia-summary-pdf"),
    path("cabinet/district/export-gia-summary-xlsx/", DownloadDistrictGiaSummaryXlsxView.as_view(), name="cabinet-district-export-gia-summary-xlsx"),
    path("cabinet/district/export-info-stat-docx/", DownloadDistrictInfoStatDocxView.as_view(), name="cabinet-district-export-info-stat-docx"),
    path("cabinet/district/export-analysis-note-docx/", DownloadDistrictAnalyticNoteDocxView.as_view(), name="cabinet-district-export-analysis-note-docx"),
    path("cabinet/district/export-subject-note-docx/", DownloadDistrictSubjectNoteDocxView.as_view(), name="cabinet-district-export-subject-note-docx"),
    path("cabinet/district/export-school-comparison-docx/", DownloadDistrictSchoolComparisonDocxView.as_view(), name="cabinet-district-export-school-comparison-docx"),
    path("cabinet/district/export-mo-report-docx/", DownloadDistrictMoReportDocxView.as_view(), name="cabinet-district-export-mo-report-docx"),
    path("cabinet/district/export-management-docx/", DownloadDistrictManagementDocxView.as_view(), name="cabinet-district-export-management-docx"),
    # Legal & documents
    path("legal/privacy/", PrivacyPolicyView.as_view(), name="legal-privacy"),
    path("legal/terms/", TermsOfAccessView.as_view(), name="legal-terms"),
    path("cabinet/documents/", SchoolDocumentsView.as_view(), name="cabinet-documents"),
    path("cabinet/documents/<slug:slug>/", SchoolDocumentDownloadView.as_view(), name="cabinet-document-download"),
]
