# Generated by Django 5.2.15 on 2026-07-20 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0002_alter_district_options_alter_ministry_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VprProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код ОО (из файла)"
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Название ОО"
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Муниципалитет"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Предмет")),
                (
                    "parallel",
                    models.PositiveSmallIntegerField(verbose_name="Класс (параллель)"),
                ),
                (
                    "academic_year",
                    models.PositiveIntegerField(verbose_name="Учебный год"),
                ),
                (
                    "exam_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата проведения"
                    ),
                ),
                (
                    "max_primary_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Макс. первичный балл"
                    ),
                ),
                (
                    "participants_count",
                    models.PositiveIntegerField(default=0, verbose_name="Участников"),
                ),
                (
                    "tasks_count",
                    models.PositiveIntegerField(default=0, verbose_name="Заданий"),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Заголовок источника"
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Лист Excel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vpr_protocols",
                        to="organizations.school",
                        verbose_name="ОО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол ВПР",
                "verbose_name_plural": "Протоколы ВПР",
                "ordering": ("-exam_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="VprStudentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_code",
                    models.CharField(max_length=64, verbose_name="Код участника"),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=255, verbose_name="ФИО"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=16, verbose_name="Пол"),
                ),
                (
                    "class_group",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Класс (группа)"
                    ),
                ),
                (
                    "variant",
                    models.CharField(blank=True, max_length=32, verbose_name="Вариант"),
                ),
                (
                    "primary_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Первичный балл",
                    ),
                ),
                (
                    "mark_vpr",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Отметка ВПР"
                    ),
                ),
                (
                    "mark_journal",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Отметка по журналу"
                    ),
                ),
                (
                    "source_row",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Строка файла"
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_results",
                        to="vpr.vprprotocol",
                        verbose_name="Протокол",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат участника ВПР",
                "verbose_name_plural": "Результаты участников ВПР",
                "ordering": ("protocol_id", "participant_code"),
                "unique_together": {("protocol", "participant_code")},
            },
        ),
        migrations.CreateModel(
            name="VprTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="Порядок")),
                ("code", models.CharField(max_length=32, verbose_name="Код задания")),
                ("title", models.CharField(max_length=64, verbose_name="Заголовок")),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Макс. балл"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Уровень сложности"
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="vpr.vprprotocol",
                        verbose_name="Протокол",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание ВПР",
                "verbose_name_plural": "Задания ВПР",
                "ordering": ("protocol_id", "position"),
                "unique_together": {("protocol", "code")},
            },
        ),
        migrations.CreateModel(
            name="VprUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="vpr/uploads/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "template_key",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Шаблон парсера"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Загружен"),
                            ("preview", "Предпросмотр"),
                            ("imported", "Импортирован"),
                            ("failed", "Ошибка"),
                            ("reverted", "Отменён"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "preview_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Предпросмотр"
                    ),
                ),
                (
                    "students_imported",
                    models.PositiveIntegerField(default=0, verbose_name="Учащихся"),
                ),
                (
                    "results_imported",
                    models.PositiveIntegerField(default=0, verbose_name="Результатов"),
                ),
                (
                    "tasks_imported",
                    models.PositiveIntegerField(default=0, verbose_name="Заданий"),
                ),
                (
                    "errors_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ошибок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обработан"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vpr_uploads",
                        to="organizations.district",
                        verbose_name="Район",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vpr_uploads",
                        to="organizations.school",
                        verbose_name="ОО",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vpr_uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Загрузка ВПР",
                "verbose_name_plural": "Загрузки ВПР",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="vprprotocol",
            name="upload",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocol",
                to="vpr.vprupload",
                verbose_name="Загрузка",
            ),
        ),
        migrations.CreateModel(
            name="VprImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Инфо"),
                            ("warning", "Предупреждение"),
                            ("error", "Ошибка"),
                        ],
                        default="info",
                        max_length=16,
                        verbose_name="Уровень",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Детали"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="vpr.vprupload",
                        verbose_name="Загрузка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог импорта ВПР",
                "verbose_name_plural": "Логи импорта ВПР",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="VprTaskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Сырое значение"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Полученный балл",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Макс. балл"
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_scores",
                        to="vpr.vprstudentresult",
                        verbose_name="Результат",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="vpr.vprtask",
                        verbose_name="Задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Балл за задание ВПР",
                "verbose_name_plural": "Баллы за задания ВПР",
                "ordering": ("result_id", "task__position"),
                "unique_together": {("result", "task")},
            },
        ),
        migrations.AddIndex(
            model_name="vprprotocol",
            index=models.Index(
                fields=["subject", "parallel", "academic_year"],
                name="vpr_vprprot_subject_435e56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vprprotocol",
            index=models.Index(
                fields=["organization_code", "academic_year"],
                name="vpr_vprprot_organiz_254195_idx",
            ),
        ),
    ]
