# Generated by Django 5.2.15 on 2026-07-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpr", "0001_initial_vpr_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VprTaskCatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="Учебный год"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Предмет"
                    ),
                ),
                (
                    "parallel",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="Класс"
                    ),
                ),
                (
                    "task_number",
                    models.PositiveSmallIntegerField(verbose_name="Номер задания"),
                ),
                (
                    "task_subnumber",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Например: 1, 2, К1, К2",
                        max_length=32,
                        verbose_name="Подномер задания",
                    ),
                ),
                (
                    "task_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Канонический код как в протоколе: 7, 9.1, 4К1",
                        max_length=64,
                        verbose_name="Код задания",
                    ),
                ),
                (
                    "official_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Официальный код",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Максимальный балл"
                    ),
                ),
                (
                    "checked_skill",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Проверяемое умение",
                    ),
                ),
                (
                    "fgos_result",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Предметный результат ФГОС",
                    ),
                ),
                (
                    "program_section",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Раздел программы",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="Тема"
                    ),
                ),
                (
                    "topic_subsection",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Подраздел темы",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Б / П / Базовый / Повышенный и т.п.",
                        max_length=32,
                        verbose_name="Уровень сложности",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Тип задания",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Краткое описание задания"
                    ),
                ),
                (
                    "normative_source",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Нормативный источник",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Расширяемые атрибуты без изменения схемы результатов",
                        verbose_name="Дополнительные поля",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Задание ВПР (справочник)",
                "verbose_name_plural": "Справочник заданий ВПР",
                "ordering": (
                    "academic_year",
                    "subject",
                    "parallel",
                    "task_number",
                    "task_subnumber",
                    "id",
                ),
                "indexes": [
                    models.Index(
                        fields=["academic_year", "subject", "parallel"],
                        name="vpr_vprtask_academi_07e659_idx",
                    ),
                    models.Index(
                        fields=["subject", "parallel", "task_code"],
                        name="vpr_vprtask_subject_f0f8cb_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "academic_year",
                            "subject",
                            "parallel",
                            "task_number",
                            "task_subnumber",
                        ),
                        name="vpr_catalog_unique_task_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VprTaskCatalogImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="vpr/catalog/%Y/%m/%d/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "source_format",
                    models.CharField(blank=True, max_length=16, verbose_name="Формат"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Успешно"),
                            ("partial", "Частично"),
                            ("failed", "Ошибка"),
                        ],
                        default="success",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(default=0, verbose_name="Создано"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="Обновлено"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ошибок"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Детали"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vpr_catalog_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Импорт справочника ВПР",
                "verbose_name_plural": "Импорты справочника ВПР",
                "ordering": ("-created_at",),
            },
        ),
    ]
