# Generated by Django 6.0.4 on 2026-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadsession',
            options={'verbose_name': 'Сессия загрузки', 'verbose_name_plural': 'Сессии загрузки'},
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('done', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20),
        ),
    ]
