# Generated by Django 5.2.15 on 2026-07-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0002_alter_district_options_alter_ministry_options_and_more",
        ),
        ("uploads", "0004_uploadsession_school_exams_revert"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_sessions",
                to="organizations.district",
                verbose_name="Район",
            ),
        ),
    ]
