# Generated by Django 5.2.15 on 2026-07-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0005_uploadsession_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsession",
            name="exam_type",
            field=models.CharField(
                choices=[("ege", "ЕГЭ"), ("oge", "ОГЭ"), ("vpr", "ВПР")], max_length=8
            ),
        ),
    ]
